### ISSUE TITLE
phantomas_view is broken

### ISSUE THREAD

**Issue by gabknight** [ecaruyer/phantomas#23]
I get this error running the script (phantomas_view 20crossing.txt):

Reading geometry description...
Traceback (most recent call last):
  File "/home/ggirard/research/phantomas/scripts/phantomas_view", line 64, in <module>
    view = ViewFiber(fiber, ren, color=color.next(), label=fiber_name)
  File "/home/ggirard/research/phantomas/phantomas/visu/views.py", line 14, in **init**
    self.init_draw(fiber, ren, **kwargs)
  File "/home/ggirard/research/phantomas/phantomas/visu/views.py", line 42, in init_draw
    stream_tube.SetInputData(poly_data)
AttributeError: SetInputData

I randomly checkout the code from PR4, and phantomas_view worked well in that previous state.

**Comment by gabknight** [comment]
This issues is fixed by PR #26, #33.
