### ISSUE TITLE
ImportError: No module named fast_volume_fraction

### ISSUE THREAD

**Issue by sbaete** [ecaruyer/phantomas#28]
After downloading and installing phantomas, I get the following when I run "phantomas_dwis -h"

Traceback (most recent call last):
  File "/usr/local/bin/phantomas_dwis", line 19, in <module>
    from phantomas.mr_simul.fod \
  File "/media/hda6/Experimenten/phantomas/phantomas/mr_simul/fod.py", line 7, in <module>
    from .fast_volume_fraction import *
ImportError: No module named fast_volume_fraction

I've tried several things and searched a bit and it seems that the cython-module fast_volume_fraction doesn't get imported correctly. However it did compile:
steven@SterlingArcher /media/hda6/Experimenten/phantomas/build/lib.linux-x86_64-2.7/phantomas/mr_simul $ ls
fast_volume_fraction  fast_volume_fraction.so  fod.py  image_formation.py  **init**.py  partial_volume.py  spherical_21_design.txt  synthetic.py
steven@SterlingArcher /media/hda6/Experimenten/phantomas/build/lib.linux-x86_64-2.7/phantomas/mr_simul $ ls fast_volume_fraction
**init**.py  pyx.so
steven@SterlingArcher /media/hda6/Experimenten/phantomas/build/lib.linux-x86_64-2.7/phantomas/mr_simul $ 

Python is novel to me, so I'm not sure how to solve it. Do you have a solution for this?

**Comment by oesteban** [comment]
Same problem here, suddenly after having phantomas working for long.

Platform is Debian Jessie.
Cython with both 0.14 and then updated to 0.22.1.

**Comment by oesteban** [comment]
I've submitted a patch that works for me. I had to manually remove everything installed system-wide. Specially, it looked important to remove the ```/usr/local/lib/python2.7/dist-packages/Phantomas-0.1.dev.egg-info``` file.
